name: Feature request
description: Suggest an idea for this project
title: "FEATURE: "
labels: [enhancement]

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary of the feature
  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
  - type: textarea
    id: details
    attributes:
      label: Detailed design or acceptance criteria
